### PR TITLE
Add arm64 Docker image

### PR DESCRIPTION
**Pull request by dennisameling**
Part of https://github.com/drud/ddev/pull/2454

**How to build**
- You'll need `docker buildx` [as described here](https://www.docker.com/blog/multi-arch-images/). Installation instructions can be found here: https://github.com/docker/buildx/#building.
- Run `make` as usual.

### CODE REVIEW

**Comment by dennisameling** [comment]
Though the build process works now and creates `arm64` and `amd64` builds, the `arm64` image is actually based on `bitnami/minideb:buster` which is `amd64`-only 😞 so this PR is blocked by https://github.com/bitnami/minideb/issues/76

**Comment by rfay** [comment]
I"m ok with trying out debian:buster-slim, it might be a great idea. . Although bitnami is a great set of images, I don't think we use any of their special features, although I always intended to... Not sure debian-slim was available back in the day. I'll bet it would work just fine.

**Comment by dennisameling** [comment]
`https://packages.sury.org` seems to be (partially) offline - both my local machine and CircleCI indicate this. I'll try again later today 👍

**Comment by dennisameling** [comment]
**arm64 and php5.6 combination** 
`arm64` misses a lot of packages for `php5.6`, so I excluded that from the `arm64` image for now. While we could support php5.6, we'd need to exclude a lot of packages for `arm64`, like `xdebug`, `memcached`, `apcu`, `redis` and probably more. Don't think leaving out 5.6 is a problem as existing `amd64` users can continue using 5.6. Might be worth mentioning in the DDEV docs though. 

**php7.4-apcu-bc**
Looking at https://packages.sury.org/php/dists/buster/main/binary-arm64/Packages, `php7.4-apcu-bc` is missing for the `arm64` architecture:

```
Package: php-apcu-bc
Version: 1.0.5-1+0~20191128.11+debian10~1.gbp90a6a0
Architecture: arm64
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 102
Pre-Depends: php-common (>= 2:69~)
Depends: php-apcu, phpapi-20180731 | phpapi-20170718 | phpapi-20160303 | phpapi-20151012, libc6 (>= 2.17)
Provides: php7.0-apcu-bc, php7.1-apcu-bc, php7.2-apcu-bc, php7.3-apcu-bc
Homepage: http://pecl.php.net/package/apcu_bc
Priority: optional
Section: php
Filename: pool/main/p/php-apcu-bc/php-apcu-bc_1.0.5-1+0~20191128.11+debian10~1.gbp90a6a0_arm64.deb
Size: 11152
SHA256: 1912322fe07a163bfdc988e43cc1b858dd3b4f268ae50dc6068c1f12c4bb35d1
SHA1: ee84a78c4d2c9b70ee562e1c4b90ad879fc131dd
MD5sum: 2d2325a12dbf161285ab9e0ef28d7748
Description: APCu Backwards Compatibility Module
 This module provides a backwards APC compatible API using APCu.
```

I've reported this at https://github.com/oerdnj/deb.sury.org/issues/1449

**Pushing to the registry**
Another thing that's important to realize, is that in the current CircleCI config you [split up the build stage and the release process](https://github.com/drud/ddev-images/blob/master/.circleci/config.yml). So the `release_build` job will use the image that was created in the `build_and_test` stage. However, for multi-arch scenarios this is currently not supported. From https://github.com/docker/buildx/#docker:

> Currently, multi-platform images cannot be exported with the docker export type. The most common usecase for multi-platform images is to directly push to a registry (see `registry`).

We could consider leveraging `docker buildx build --push ......` in the `release_build` stage, which will build the images and push to the registry right away. At the moment I'm not sure if we can use the images built from `build_and_test` so it would re-build in the `release_build` stage. Any thoughts on this @rfay?

**Build times**
Because the build process for `arm64` uses [QEMU emulation](https://github.com/docker/buildx#building-multi-platform-images) (there aren't any native `arm64` build hosts in CircleCI AFAIK), the build process is now considerably slower. It has gone from [3m 58s](https://app.circleci.com/pipelines/github/drud/ddev-images/136/workflows/3aaeeb65-b48c-4e43-8ecc-948e92340f65/jobs/143) to _(WIP still running)_. Hope that's okay for now.

**Comment by dennisameling** [comment]
I was able to build `ddev-images` for arm64 and pushed a test version to https://hub.docker.com/repository/docker/dennisameling/ddev-php-base/tags?page=1 🚀 

Here you can see that PHP indeed is compiled for `arm64` (`aarch64`):

```
$ docker run -it dennisameling/ddev-php-base:20200817
root@f04034582e4e:/# php -a
Interactive mode enabled

php > echo php_uname();
Linux f04034582e4e 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:45:06 UTC 2020 aarch64
```

If we can tackle the issues I mentioned above, then we should be good to go to release multi-arch images 😊

**Comment by rfay** [comment]
Awesome work!

* I think it's fine to leave out php5.6 for now.
* We'll probably want to figure out how to parallelize the build process. I hate for every CircleCI to *start* with an hour build.

**Review by rfay — APPROVED** [review]
Looks great, thanks!

**Comment by rfay** [comment]
Unfortunately I didn't read closely enough in https://github.com/drud/ddev-images/pull/16#issuecomment-674861160 so now master is broken and we can't deploy the official version. It will just take some attention. I'll come back to it soon.

**Pull request merged**
